### ISSUE TITLE
I installed via Melpa but not loading

### ISSUE THREAD

**Issue by tbrooke** [ethereum/emacs-solidity#3]
This may not be the right place to ask but I get FIle mode specification error: (void-function  solidity-mode)

**Comment by LefterisJP** [comment]
This is the right place to ask. Can you do ```M-x toggle-debug-on-error``` and then reproduce the problem and copy the call trace in the issue?

**Comment by tbrooke** [comment]
Debugger entered--Lisp error: (void-function solidity-mode)
  solidity-mode()
  set-auto-mode-0(solidity-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer clientreceipt.sol> "~/eth/dapp-bin/clientreceipt/clientreceipt.sol" nil nil "~/eth/dapp-bin/cl$
  find-file-noselect("/Users/tmb/eth/dapp-bin/clientreceipt/clientreceipt.sol" nil nil nil)
  find-file("/Users/tmb/eth/dapp-bin/clientreceipt/clientreceipt.sol")
  find-file-existing("/Users/tmb/eth/dapp-bin/clientreceipt/clientreceipt.sol")

**Comment by santiagorp** [comment]
I have the same error. Some ideas? I use emacs 24.5.1

Thanks!

**Comment by bl4ck5un** [comment]
Same problem here. Any idea?

**Comment by LefterisJP** [comment]
I will have a look tomorrow. Will keep you guys up to date. Installing from [el-get](https://github.com/dimitri/el-get) works since I use it from there but perhaps there is an issue with Melpa.

I will fix it as soon as I can reproduce it.

**Comment by LefterisJP** [comment]
@bl4ck5un @santiagorp 

How did you try to install the package?
Did you require the package somewhere in your emacs configuration?
```lisp
(require 'solidity-mode)
```

**Comment by santiagorp** [comment]
Actually now it seems to be working. But still I get some warnings during installation:

These are the steps I follow:
1. Start emacs, then M-x package-list
2. Search for solidity-mode (currently the version is 2016.04.26)
3. Mark to install it and click install

I get the following warnings on the emacs console:
Compiling file /home/santi/.emacs.d/elpa/solidity-mode-20160426.31/solidity-mode-autoloads.el at Thu May  5 09:22:46 2016
Entering directory `/home/santi/.emacs.d/elpa/solidity-mode-20160426.31/'
Compiling file /home/santi/.emacs.d/elpa/solidity-mode-20160426.31/solidity-mode-pkg.el at Thu May  5 09:22:46 2016
Compiling file /home/santi/.emacs.d/elpa/solidity-mode-20160426.31/solidity-mode.el at Thu May  5 09:22:46 2016
solidity-mode.el:383:1:Warning: `"/usr/bin/solc"' is a malformed function
solidity-mode.el:383:1:Warning: `(error line-start (file-name) ":" line ":"
    column ":" " Error: " (message))' is a malformed function
solidity-mode.el:386:28:Warning: reference to free variable `solidity'
solidity-mode.el:388:31:Warning: reference to free variable `source-inplace'
solidity-mode.el:391:12:Warning: reference to free variable `solidity-mode'
solidity-mode.el:393:17:Warning: reference to free variable
    `flycheck-checkers'
solidity-mode.el:393:17:Warning: assignment to free variable
    `flycheck-checkers'
solidity-mode.el:395:30:Warning: assignment to free variable
    `flycheck-solidity-executable'

In end of data:
solidity-mode.el:399:1:Warning: the function `flycheck-define-checker' is not
    known to be defined.

I have solidity compiler installed:
$> /usr/bin/solc --version
solc, the solidity compiler commandline interface
Version: 0.3.2-81ae2a78/Release-Linux/g++/JIT

After adding the (required 'solidity-mode) to my .emacs I see the syntax and seems to be working now. However I am not sure if the warnings during install are intended to be there.

Kind regards,

Santiago

**Comment by LefterisJP** [comment]
Thank you for the very detailed report @santiagorp.

I also get 2 of these warnings. I am using a custom `solc` so I am not sure why you are getting that `solc` warning, I will have to check.

As for the reason to the actual warnings, I am not sure of the proper way to get rid of them. Will look around and try to figure it out.

**Comment by LefterisJP** [comment]
Fixed some of the warnings. Will see if I can handle the rest at some point later, but they are mainly harmless.

As for the original issue this should be fixed so I am closing this now. Please open additional issues for any further problems.

**Comment by paulperegud** [comment]
By @bmag at https://gitter.im/syl20bnr/spacemacs

> I found the problem. solidity-mode does not define an autoload for its major-mode (see [here](https://github.com/ethereum/emacs-solidity/blob/master/solidity-mode.el#L358)), so you need to require it in user-config
see [here](https://github.com/hlissner/emacs-pug-mode/blob/master/pug-mode.el#L257-L258) for a proper autoloaded major-mode. I'd suggest reporting the missing autoload as a bug

**Comment by LefterisJP** [comment]
@paulperegud Thank you Paul. I will use his examples and try to provide a fix. PRs are always welcome!

**Comment by LefterisJP** [comment]
@paulperegud I added the magic autoload comment as defined in the [emacs wiki](https://ftp.gnu.org/old-gnu/Manuals/elisp-manual-21-2.8/html_node/elisp_199.html).

Can you check if your configuration is working better now?

**Comment by paulperegud** [comment]
@LefterisJP 

No, it does not fix loading. I've tried adding this line myself, to no avail. 

Since you've asked for my env, here it is.

    $ emacs --version
    GNU Emacs 24.5.1

And .spacemacs to replicate the issue:

https://gist.github.com/paulperegud/9302694f388410071ae31cecccefc7f9
Note: this is a autogenerated .spacemacs with two extra lines marked with ";; PP:" comment

Installation steps:
1. git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
2. download ~/.spacemacs from gist above
3. run emacs (when asked I choose "evil flagship" / "standard distribution" but I don't think the choice is relevant to this bug)

**Comment by paulperegud** [comment]
To force spacemacs to recompile it's configuration use "SPC f e d" to go to .spacemacs file, "SPC f s" to save it, "SPC f e R" to run configuration update process.

**Comment by bmag** [comment]
@LefterisJP @paulperegud you need to wait for [MELPA](https://melpa.org/) to catch up on the changes. It usually takes less than 5 hours.

> To force spacemacs to recompile it's configuration use "SPC f e d" to go to .spacemacs file, "SPC f s" to save it, "SPC f e R" to run configuration update process.

That's not a re-compile, that's a reload. Recompile is something different, and has to do with `elc` files. To install the new version of the package (once it's available from MELPA), you need to either delete the `solidity-mode` directory inside `~/.emacs.d/elpa/`, or use the "Update Packages" button in Spacemacs home buffer.

**Comment by tbrooke** [comment]
I am using Spacemacs and Emacs v 25 

I was receiving this error message (see [Issue 8](https://github.com/ethereum/emacs-solidity/issues/8))
```

Compiling file /home/victor/.emacs.d/elpa/solidity-mode-20160426.31/solidity-mode.el at Fri Apr 29 13:21:06 2016
solidity-mode.el:383:1:Warning: `"/usr/bin/solc"' is a malformed function
solidity-mode.el:383:1:Warning: `(error line-start (file-name) ":" line ":"
    column ":" " Error: " (message))' is a malformed function
solidity-mode.el:386:28:Warning: reference to free variable `solidity'
solidity-mode.el:388:31:Warning: reference to free variable `source-inplace'
solidity-mode.el:391:12:Warning: reference to free variable `solidity-mode'
solidity-mode.el:393:17:Warning: reference to free variable
    `flycheck-checkers'
solidity-mode.el:393:17:Warning: assignment to free variable
    `flycheck-checkers'
solidity-mode.el:395:30:Warning: assignment to free variable
    `flycheck-solidity-executable'
```

I commented out the following and it works fine, but I guess I don't have flycheck:

```

;;; --- interface with flycheck if existing ---
(when (require 'flycheck nil 'noerror)
  ;; add dummy source-inplace definition to avoid errors
  (defvar source-inplace)
  ;; add a solidity mode callback to set the executable of solc for flycheck
  ;; define solidity's flycheck syntax checker
  (flycheck-define-checker solidity-checker
    "A Solidity syntax checker using the solc compiler"
    :command ("/usr/bin/solc" source-inplace)
    :error-patterns
    ((error line-start (file-name) ":" line ":" column ":" " Error: " (message)))
    :modes solidity-mode
    :predicate (lambda () (eq major-mode 'solidity-mode)))
  (add-to-list 'flycheck-checkers 'solidity-checker)
  (add-hook 'solidity-mode-hook
            (lambda () (setq flycheck-solidity-executable solidity-solc-path))))

```

**Comment by LefterisJP** [comment]
@tbrooke That appears to be a different issue. Can you make a new issue and paste what you wrote there?

**Comment by LefterisJP** [comment]
@bmag @paulperegud Great to hear. I am not familiar with spacemacs, I ofcourse know of Melpa but use `el-get` myself. 

If the loading issue is resolved for all of you then please tell me and I will close the issue. If not I will play with spacemacs to see what is wrong.

**Comment by tbrooke** [comment]
I did ["/usr/bin/solc"' is a malformed function #8](https://github.com/ethereum/emacs-solidity/issues/8) But I guess I wasn't clear so I reposted it

**Comment by LefterisJP** [comment]
@paulperegud @bmag Both in normal emacs melpa and in spacemacs with the configuration you provided solidity mode seems to be auto-loaded fine right now.

Only at spacemacs there seems to be the issue @tbrooke reported though, but I will address this in the other issue.

If it's okay with you @paulperegud and you can confirm it's fine now I will close the ticket.

**Comment by paulperegud** [comment]
@LefterisJP problem is fixed, confirming!

**Comment by LefterisJP** [comment]
Thanks Paul!
